; Этот файл является файлом конфигурации прокси библиотеки.
; При его отсутствии будет использоваться конфигурация по умолчанию.

; APPDIR - этот параметр определяет как учитывается путь к DATADIR и CACHEDIR.
; Если APPDIR=1 используется абсолютный путь к DATADIR и CACHEDIR с учетом расположения исполняемого файла. Конфигурация по умолчанию.
; Если APPDIR=0 используется относительный путь к DATADIR и CACHEDIR или при необходимости можно указать полный абсолютный путь.
; REGOFF - этот параметр определяет включена или нет функция блокировки записи в реестр.
; Если REGOFF=1 функция блокировки записи в реестр включена. Конфигурация по умолчанию.
; Если REGOFF=0 функция блокировки записи в реестр отключена.
; AIDOFF - этот параметр определяет включена или нет функция блокировки идентификации программы.
; Если AIDOFF=1 функция блокировки идентификации включена. Конфигурация по умолчанию.
; Если AIDOFF=0 функция блокировки идентификации отключена.
; DIROFF - этот параметр определяет включена или нет функция удаления файлов и удаления и блокировки директорий по списку. 
; Если DIROFF=1 функция удаления файлов и удаления и блокировки директорий включена.
; Если DIROFF=0 функция удаления файлов и удаления и блокировки директорий отключена. Конфигурация по умолчанию.

[Parameters]
APPDIR=1
REGOFF=1
AIDOFF=1
DIROFF=1

; DATADIR - это путь к директории где будут расположены  данные пользовател. Путь по умолчанию User Data.
; CACHEDIR - это путь к директории где будут расположены данные кеша. Путь по умолчанию Cache.
; Если CACHEDIR=nul - тогда использование кеша будет отключено.
; RUNPARAM - это дополнительные параметры запуска. Все параметры запуска должны быть в одной строке. После каждого параметра обязательно добавить пробел.

[General]
DATADIR=User Data
CACHEDIR=Cache
RUNPARAM=--disable-logging --no-report-upload --disable-gpu-shader-disk-cache --user-agent="Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 YaBrowser/24.6.0.0 Safari/537.36" 

; Список файлов и директорий для удаления и блокировки
; каждая строка списка для удаления и блокировки директорий должна начинаться с DeleteDir=
; после DeleteDir= должен быть указан абсолютный или относительный путь к директории. Регистр в именах должен совпадать.
; каждая строка списка для удаления файлов должна начинаться с DeleteFile=
; после DeleteFile= должен быть указан абсолютный или относительный путь к файлу. 

[DirList]
; Директории данных
DeleteDir=.\User Data\AutofillStates
DeleteDir=.\User Data\BrowserMetrics
DeleteDir=.\User Data\CertificateRevocation
DeleteDir=.\User Data\component_crx_cache
DeleteDir=.\User Data\Crashpad\attachments
DeleteDir=.\User Data\Crashpad\reports
DeleteDir=.\User Data\Crowd Deny
DeleteDir=.\User Data\FileTypePolicies
DeleteDir=.\User Data\FirstPartySetsPreloaded
DeleteDir=.\User Data\hyphen-data
DeleteDir=.\User Data\MEIPreload
DeleteDir=.\User Data\OnDeviceHeadSuggestModel
DeleteDir=.\User Data\OptimizationHints
DeleteDir=.\User Data\OriginTrials
DeleteDir=.\User Data\PKIMetadata
DeleteDir=.\User Data\PrivacySandboxAttestationsPreloaded
DeleteDir=.\User Data\SafetyTips
DeleteDir=.\User Data\SSLErrorAssistant
DeleteDir=.\User Data\Subresource Filter
DeleteDir=.\User Data\TrustTokenKeyCommitments
DeleteDir=.\User Data\WidevineCdm
DeleteDir=.\User Data\ZxcvbnData
; Директории профиля по умолчанию
DeleteDir=.\User Data\Default\AutofillStrikeDatabase
DeleteDir=.\User Data\Default\blob_storage
DeleteDir=.\User Data\Default\BudgetDatabase
DeleteDir=.\User Data\Default\commerce_subscription_db
DeleteDir=.\User Data\Default\coupon_db
DeleteDir=.\User Data\Default\databases
DeleteDir=.\User Data\Default\discounts_db
DeleteDir=.\User Data\Default\Feature Engagement Tracker
DeleteDir=.\User Data\Default\GCM Store
;DeleteDir=.\User Data\Default\IndexedDB
DeleteDir=.\User Data\Default\JumpListIconsRecentClosed
DeleteDir=.\User Data\Default\optimization_guide_hint_cache_store
DeleteDir=.\User Data\Default\optimization_guide_model_metadata_store
DeleteDir=.\User Data\Default\Segmentation Platform
DeleteDir=.\User Data\Default\Service Worker
DeleteDir=.\User Data\Default\shared_proto_db
DeleteDir=.\User Data\Default\Site Characteristics Database
DeleteDir=.\User Data\Default\VideoDecodeStats
;DeleteDir=.\User Data\Default\WebStorage

[FileList]
; Файлы данных
DeleteFile=.\User Data\first_party_sets.db
DeleteFile=.\User Data\first_party_sets.db-journal
DeleteFile=.\User Data\BrowserMetrics-spare.pma
; Файлы профиля по умолчанию
DeleteFile=.\User Data\Default\Affiliation Database
DeleteFile=.\User Data\Default\Affiliation Database-journal
DeleteFile=.\User Data\Default\LOG
DeleteFile=.\User Data\Default\LOG.old
DeleteFile=.\User Data\Default\heavy_ad_intervention_opt_out.db
DeleteFile=.\User Data\Default\heavy_ad_intervention_opt_out.db-journal
DeleteFile=.\User Data\Default\trusted_vault.pb