; Этот файл является файлом конфигурации прокси библиотеки.
; При его отсутствии будет использоваться конфигурация по умолчанию.

; APPDIR - этот параметр определяет как учитывается путь к DATADIR и CACHEDIR.
; Если APPDIR=1 будет использоваться абсолютный путь к DATADIR и CACHEDIR с учетом расположения исполняемого файла. Конфигурация по умолчанию.
; Если APPDIR=0 будет использоваться относительный путь к DATADIR и CACHEDIR или при необходимости можно указать полный абсолютный путь вручню.
; REGOFF - этот параметр определяет включена или нет функция блокировки записи в реестр.
; Если REGOFF=1 функция блокировки записи в реестр включена. Конфигурация по умолчанию.
; Если REGOFF=0 функция блокировки записи в реестр отключена.
; AIDOFF - этот параметр определяет включена или нет функция блокировки идентификации программы.
; Если AIDOFF=1 функция блокировки идентификации включена. Конфигурация по умолчанию.
; Если AIDOFF=0 функция блокировки идентификации отключена.
; DIROFF - этот параметр определяет включена или нет функция удаления файлов и директорий и блокировки директорий по списку. 
; Если DIROFF=1 функция удаления файлов и директорий и блокировки директорий включена.
; Если DIROFF=0 функция удаления файлов и директорий и блокировки директорий отключена. Конфигурация по умолчанию.
; RMDISK - этот параметр определяет включена или нет функция определения пути к файлам в директории TEMP на рам диске. 
; Если RMDISK=1 функция определения пути к файлам в директории TEMP на рам диске включена.
; Если RMDISK=0 функция определения пути к файлам в директории TEMP на рам диске отключена. Конфигурация по умолчанию.
; REFINE - этот параметр определяет включена или нет функция обнуления запросов к серверам гугла и его сателлитам.
; Если REFINE=1 функция обнуления запросов к серверам включена. Конфигурация по умолчанию.
; Если REFINE=0 функция обнуления запросов к серверам отключена.
; SPFOLD - этот параметр определяет включена или нет функция задания пути к спецпапкам.
; Если SPFOLD=1 функция задания пути к спецпапкам включена.
; Если SPFOLD=0 функция задания пути к спецпапкам отключена. Конфигурация по умолчанию.
; BCTOFF - этот параметр определяет включена или нет функция блокировки широковещательных рассылок.
; Если BCTOFF=1 функция блокировки широковещательных рассылок включена. Конфигурация по умолчанию.
; Если BCTOFF=0 функция блокировки широковещательных рассылок отключена.
; STARTM - этот параметр определяет метод запуска браузера.
; Если STARTM=1 запуск осуществляется функцией CreateProcess.
; Если STARTM=0 запуск осуществляется функцией ShellExecuteEx. Конфигурация по умолчанию.
; ECHOFF - этот параметр определяет включена или нет функция блокировки DoH и ECH.
; Если ECHOFF=1 функция блокировки DoH и ECH включена.
; Если ECHOFF=0 функция блокировки DoH и ECH отключена. Конфигурация по умолчанию.

[Parameters]
APPDIR=1
REGOFF=1
AIDOFF=1
DIROFF=1
RMDISK=1
REFINE=1
SPFOLD=0
BCTOFF=1
STARTM=0
ECHOFF=0

; DATADIR - это путь к директории где будут расположены  данные пользовател. Путь по умолчанию User Data.
; CACHEDIR - это путь к директории где будут расположены данные кеша. Путь по умолчанию Cache.
; Если CACHEDIR=nul - тогда использование кеша будет отключено.
; SPECFOLDER - это путь, который будет исползоваться как путь к спецпапкам. Путь может быть относительный или абсолютный.
; Например ..\User Data или A:\Temp. Если SPECFOLDER=nul - тогда файлы в спецпапках создаваться не будут.
; RUNPARAM - это дополнительные параметры запуска. Все параметры запуска должны быть в одной строке. После каждого параметра обязательно добавить пробел.

[General]
DATADIR=User Data
CACHEDIR=Cache
SPECFOLDER=..\User Data
RUNPARAM=--disable-logging --no-report-upload --disable-gpu-shader-disk-cache --disable-component-update --disable-background-networking --user-agent="Mozilla/5.0 (Windows NT 5.1) Chrome/134.0.0.0 YaBrowser/25.2.8.99 Safari/537.36" 

; Список директорий для удаления и блокировки
; каждая строка списка для удаления и блокировки директорий должна начинаться с DeleteDir=
; после DeleteDir= должен быть указан абсолютный или относительный путь к директории.

[DirList]
; Директории данных
DeleteDir=%DATADIR%\AutofillStates
DeleteDir=%DATADIR%\BrowserMetrics
DeleteDir=%DATADIR%\CertificateRevocation
DeleteDir=%DATADIR%\component_crx_cache
DeleteDir=%DATADIR%\Crashpad\attachments
DeleteDir=%DATADIR%\Crashpad\reports
DeleteDir=%DATADIR%\Crowd Deny
DeleteDir=%DATADIR%\FileTypePolicies
DeleteDir=%DATADIR%\FirstPartySetsPreloaded
DeleteDir=%DATADIR%\hyphen-data
DeleteDir=%DATADIR%\MEIPreload
DeleteDir=%DATADIR%\OnDeviceHeadSuggestModel
DeleteDir=%DATADIR%\OptimizationHints
DeleteDir=%DATADIR%\OriginTrials
DeleteDir=%DATADIR%\PKIMetadata
DeleteDir=%DATADIR%\PrivacySandboxAttestationsPreloaded
DeleteDir=%DATADIR%\SafetyTips
DeleteDir=%DATADIR%\SSLErrorAssistant
DeleteDir=%DATADIR%\Subresource Filter
DeleteDir=%DATADIR%\TrustTokenKeyCommitments
DeleteDir=%DATADIR%\WidevineCdm
DeleteDir=%DATADIR%\ZxcvbnData
; Директории профиля по умолчанию
DeleteDir=%DATADIR%\Default\AutofillStrikeDatabase
DeleteDir=%DATADIR%\Default\blob_storage
DeleteDir=%DATADIR%\Default\BudgetDatabase
DeleteDir=%DATADIR%\Default\commerce_subscription_db
DeleteDir=%DATADIR%\Default\coupon_db
DeleteDir=%DATADIR%\Default\databases
DeleteDir=%DATADIR%\Default\discounts_db
DeleteDir=%DATADIR%\Default\Feature Engagement Tracker
DeleteDir=%DATADIR%\Default\GCM Store
;DeleteDir=%DATADIR%\Default\IndexedDB
DeleteDir=%DATADIR%\Default\JumpListIconsRecentClosed
DeleteDir=%DATADIR%\Default\optimization_guide_hint_cache_store
DeleteDir=%DATADIR%\Default\optimization_guide_model_metadata_store
DeleteDir=%DATADIR%\Default\Segmentation Platform
DeleteDir=%DATADIR%\Default\Service Worker
DeleteDir=%DATADIR%\Default\shared_proto_db
DeleteDir=%DATADIR%\Default\Site Characteristics Database
DeleteDir=%DATADIR%\Default\VideoDecodeStats
;DeleteDir=%DATADIR%\Default\WebStorage

; Список файлов для удаления
; каждая строка списка для удаления файлов должна начинаться с DeleteFile=
; после DeleteFile= должен быть указан абсолютный или относительный путь с именем файла или шаблоном (в шаблоне обязательно присутствие символа *).

[FileList]
; Файлы данных
DeleteFile=%DATADIR%\*.db
DeleteFile=%DATADIR%\*-journal
DeleteFile=%DATADIR%\BrowserMetrics-spare.pma
; Файлы профиля по умолчанию
DeleteFile=%DATADIR%\Default\*.db
DeleteFile=%DATADIR%\Default\*-journal
DeleteFile=%DATADIR%\Default\Affiliation Database
DeleteFile=%DATADIR%\Default\LOG
DeleteFile=%DATADIR%\Default\LOG.old
DeleteFile=%DATADIR%\Default\trusted_vault.pb

; Список серверов гугла и его сателлитов к которым обнуляются запросы
; каждая строка списка должна начинаться с NullDomain=
; после NullDomain= должен быть указан адрес сервера полностью или частично

[REFINELIST]
NullDomain=amazon
NullDomain=account.google.com
NullDomain=accounts.google.com
NullDomain=adssettings.google.com
NullDomain=adgoogle
NullDomain=adsense.google.com
NullDomain=advisor.google.com
NullDomain=adwords.google.com
NullDomain=adservice.google
NullDomain=analytics.google
NullDomain=analytics.firebaseapp.com
NullDomain=android.clients.google
NullDomain=arin.net
NullDomain=apps.db.ripe.net
NullDomain=clients2.google
NullDomain=clients.your-server
NullDomain=clickserver.googleads.com
NullDomain=cloudflare
NullDomain=crashlytics
NullDomain=cse.google.com
NullDomain=ghs.google.com
NullDomain=dl.google
NullDomain=events.google.com
NullDomain=explorer.apis.google.com
NullDomain=express.google.com
NullDomain=ext.google.com
NullDomain=face-indexing.com
NullDomain=face-mining.com
NullDomain=faceindexing.com
NullDomain=facemining.com
NullDomain=facesort.com
NullDomain=fundingchoicesmessages.google.com
NullDomain=googlevads
NullDomain=googleads.g.doubleclick
NullDomain=googlehosted
NullDomain=googleadservices
NullDomain=googleoptimize
NullDomain=googlesyndication
NullDomain=googleusercontent
NullDomain=google-analytics
NullDomain=googleapis
NullDomain=googletagmanager
NullDomain=googleanalytics
NullDomain=googletagservices
NullDomain=gstatic
NullDomain=netblocks
NullDomain=maps.google  
NullDomain=mtalk.google
NullDomain=peoplestackwebexperiments-pa.clients6.google.com
NullDomain=rdap.arin.net
NullDomain=sb.l.google
NullDomain=script.google.com
NullDomain=static.doubleclick.net
NullDomain=spf.google.com
NullDomain=tagmanager.google.com
NullDomain=tcp.google.com
NullDomain=tls.google.com
NullDomain=unpkg.com
NullDomain=wide-plus.l.google
NullDomain=withgoogle