; Этот файл является файлом конфигурации прокси библиотеки.
; Если удалить этот файл тогда будет использоваться конфигурация по умолчанию.

; APPDIR - этот параметр определяет абсолютный или относительный путь к DATADIR и CACHEDIR.
; Если APPDIR=1 тогда будет автоматически определяться абсолютный путь к DATADIR и CACHEDIR с учетом расположения исполняемого файла.
; Если APPDIR=0 тогда будет использоваться относительный путь к DATADIR и CACHEDIR или при необходимости можно указать абсолютный путь.

[Parameters]
APPDIR=1

; DATADIR - это путь к директории где будут расположены  данные пользовател¤. Если путь не указан будет использоваться путь по умолчанию.
; CACHEDIR - это путь к директории где будут расположены данные кеша. Если путь не указан будет использоватьс¤ путь по умолчанию.
; Если CACHEDIR=nul - тогда использование кеша будет отключено.
; RUNPARAM - это дополнительные параметры запуска. Все параметры запуска должны быть в одной строке. После каждого параметра обязательно добавить пробел.

[General]
DATADIR=User Data
CACHEDIR=Cache
RUNPARAM=--disable-logging --no-report-upload 